services:
  springboot-app:
    build: .
    ports:
      - "8229:8090"  # Aquí el puerto 8229 lo cambias por tu puerto asignado
    volumes:
      - ./logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod

